# Bank Customer Churn Prediction & Business Intelligence

### Objective

Analyze customer behavior, identify factors contributing to customer churn,
build a predictive machine learning model,
and create a Power BI dashboard to support business decision-making.

Author: Avishek Chatterjee

In [2]:
# ==============================
# Import Required Libraries
# ==============================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

sns.set_style("whitegrid")

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [4]:
# Load Dataset

df = pd.read_csv("../data/churn_prediction.csv")

In [5]:
df.head()

   customer_id  vintage  age gender  dependents     occupation    city  customer_nw_category  branch_code  current_balance  previous_month_end_balance  average_monthly_balance_prevQ  average_monthly_balance_prevQ2  current_month_credit  previous_month_credit  current_month_debit  previous_month_debit  current_month_balance  previous_month_balance  churn last_transaction
0            1     2101   66   Male         0.0  self_employed   187.0                     2          755          1458.71                     1458.71                        1458.71                         1449.07                  0.20                   0.20                 0.20                  0.20                1458.71                 1458.71      0       2019-05-21
1            2     2348   35   Male         0.0  self_employed     NaN                     2         3214          5390.37                     8704.66                        7799.26                        12419.41                  0.56                   0.56              5486.27                100.56                6496.78                 8787.61      0       2019-11-01
2            4     2194   31   Male         0.0       salaried   146.0                     2           41          3913.16                     5815.29                        4910.17                         2815.94                  0.61                   0.61              6046.73                259.23                5006.28                 5070.14      0              NaT
3            5     2329   90    NaN         NaN  self_employed  1020.0                     2          582          2291.91                     2291.91                        2084.54                         1006.54                  0.47                   0.47                 0.47               2143.33                2291.91                 1669.79      1       2019-08-06
4            6     1579   42   Male         2.0  self_employed  1494.0                     3          388           927.72                     1401.72                        1643.31                         1871.12                  0.33                 714.61               588.62               1538.06                1157.15                 1677.16      1       2019-11-03

In [6]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 28382
Columns: 21

In [7]:
df.columns.tolist()

['customer_id',
 'vintage',
 'age',
 'gender',
 'dependents',
 'occupation',
 'city',
 'customer_nw_category',
 'branch_code',
 'current_balance',
 'previous_month_end_balance',
 'average_monthly_balance_prevQ',
 'average_monthly_balance_prevQ2',
 'current_month_credit',
 'previous_month_credit',
 'current_month_debit',
 'previous_month_debit',
 'current_month_balance',
 'previous_month_balance',
 'churn',
 'last_transaction']

In [8]:
df.describe().T

                                  count          mean           std       min        25%        50%         75%          max
customer_id                     28382.0  15143.508667   8746.454456      1.00  7557.2500  15150.500  22706.7500     30301.00
vintage                         28382.0   2091.144105    272.676775     73.00  1958.0000   2154.000   2292.0000      2476.00
age                             28382.0     48.208336     17.807163      1.00    36.0000     46.000     60.0000        90.00
dependents                      25919.0      0.347236      0.997661      0.00     0.0000      0.000      0.0000        52.00
city                            27579.0    796.109576    432.872102      0.00   409.0000    834.000   1096.0000      1649.00
customer_nw_category            28382.0      2.225530      0.660443      1.00     2.0000      2.000      3.0000         3.00
branch_code                     28382.0    925.975019    937.799129      1.00   176.0000    572.000   1440.0000      4782.00
current_balance                 28382.0   7380.551804  42598.711923  -5503.96  1784.4700   3281.255   6635.8200   5905904.03
previous_month_end_balance      28382.0   7495.770548  42529.345225  -3149.57  1906.0000   3379.915   6656.5350   5740438.63
average_monthly_balance_prevQ   28382.0   7496.779856  41726.218776   1428.69  2180.9450   3542.865   6666.8875   5700289.57
average_monthly_balance_prevQ2  28382.0   7124.209162  44575.809640 -16506.10  1832.5075   3359.600   6517.9600   5010170.10
current_month_credit            28382.0   3433.252240  77071.452408      0.01     0.3100      0.610    707.2725  12269845.39
previous_month_credit           28382.0   3261.694458  29688.889329      0.01     0.3300      0.630    749.2350   2361808.29
current_month_debit             28382.0   3658.744549  51985.423665      0.01     0.4100     91.930   1360.4350   7637857.36
previous_month_debit            28382.0   3339.761353  24301.111683      0.01     0.4100    109.960   1357.5525   1414168.06
current_month_balance           28382.0   7451.132765  42033.938543  -3374.18  1996.7650   3447.995   6667.9575   5778184.77
previous_month_balance          28382.0   7495.177129  42431.978814  -5171.92  2074.4075   3465.235   6654.6925   5720144.50
churn                           28382.0      0.185329      0.388571      0.00     0.0000      0.000      0.0000         1.00

In [9]:
df.isnull().sum()

customer_id                          0
vintage                              0
age                                  0
gender                             525
dependents                        2463
occupation                          80
city                               803
customer_nw_category                 0
branch_code                          0
current_balance                      0
previous_month_end_balance           0
average_monthly_balance_prevQ        0
average_monthly_balance_prevQ2       0
current_month_credit                 0
previous_month_credit                0
current_month_debit                  0
previous_month_debit                 0
current_month_balance                0
previous_month_balance               0
churn                                0
last_transaction                     0
dtype: int64

In [10]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [11]:
df.to_csv("../data/bank_churn_clean.csv", index=False)